# Generated by Django 5.2.7 on 2025-10-19 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('declaraciones', '0001_initial'),
        ('instrumentos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_factor', models.FloatField()),
                ('fecha_factor', models.DateField()),
                ('regimen', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=200)),
                ('secuencia_evento', models.IntegerField()),
                ('dividendo', models.FloatField()),
                ('valor_historico', models.FloatField()),
                ('año_tributario', models.DateField()),
                ('isfut', models.BooleanField(default=False)),
                ('origen', models.CharField(max_length=80)),
                ('estado_tributario', models.CharField(max_length=50)),
                ('declaracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaraciones.declaracionjurada')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.instrumento')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.factormensual')),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Detalles del error encontrado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado')], default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_creados', to='usuarios.usuario')),
            ],
        ),
    ]
