# Generated by Django 5.2.7 on 2025-11-07 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('declaraciones', '0002_cargaarchivo'),
        ('instrumentos', '0001_initial'),
        ('usuarios', '0007_alter_usuario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor_factor', models.FloatField()),
                ('fecha_factor', models.DateField()),
                ('carga_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='declaraciones.cargaarchivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('secuencia_evento', models.IntegerField()),
                ('dividendo', models.FloatField()),
                ('valor_historico', models.FloatField()),
                ('año_tributario', models.IntegerField()),
                ('isfut', models.BooleanField(default=False)),
                ('estado_tributario', models.CharField(default='Activo', max_length=50)),
                ('declaracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='declaraciones.declaracionjurada')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.instrumento')),
                ('origen', models.ForeignKey(blank=True, help_text='Carga de archivo que originó esta calificación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='declaraciones.cargaarchivo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.factormensual')),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Detalles del error encontrado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('area_afectada', models.CharField(default='Panel de calificacion', max_length=90)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado')], default='pendiente', max_length=20)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='reportes_evidencias/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_creados', to='usuarios.usuario')),
            ],
        ),
    ]
