# Generated by Django 5.2.7 on 2025-10-25 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='año_tributario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='estado_tributario',
            field=models.CharField(default='Activo', max_length=50),
        ),
    ]
