# Generated by Django 5.2.7 on 2025-10-29 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_calificaciontributaria_usuario_and_more'),
        ('declaraciones', '0002_cargaarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factormensual',
            name='carga_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='declaraciones.cargaarchivo'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='origen',
            field=models.ForeignKey(blank=True, help_text='Carga de archivo que originó esta calificación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='declaraciones.cargaarchivo'),
        ),
    ]
