# Generated by Django 5.2.7 on 2025-11-07 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_calificaciontributaria_instrumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auditoria.factormensual'),
        ),
    ]
