# Generated by Django 5.2.7 on 2025-10-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_factormensual_carga_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='area_afectada',
            field=models.CharField(default='Panel de calificacion', max_length=90),
        ),
    ]
