# Generated by Django 5.2.7 on 2025-11-07 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_alter_calificaciontributaria_factor'),
        ('instrumentos', '0001_initial'),
        ('usuarios', '0007_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='instrumento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='instrumentos.instrumento'),
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
