# Generated by Django 5.2.7 on 2025-11-09 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_alter_calificaciontributaria_instrumento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='factor',
        ),
        migrations.AddField(
            model_name='factormensual',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditoria.calificaciontributaria'),
        ),
    ]
