# Generated by Django 5.2.5 on 2025-11-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_reportes_area_afectada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='reportes_evidencias/'),
        ),
    ]
