# Generated by Django 5.2.7 on 2025-11-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_reportes_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factormensual',
            name='regimen',
        ),
        migrations.AddField(
            model_name='factormensual',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
