# Generated by Django 5.2.7 on 2025-11-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_remove_calificaciontributaria_factor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factormensual',
            options={'ordering': ['numero_factor']},
        ),
        migrations.AddField(
            model_name='factormensual',
            name='numero_factor',
            field=models.IntegerField(default=0),
        ),
    ]
