# Generated by Django 5.2.7 on 2025-11-19 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_alter_factormensual_options_and_more'),
        ('instrumentos', '0002_alter_mercado_codigo_mercado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablaAfectada', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('usuario', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'auditoria_log',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instrumentos.instrumento'),
        ),
    ]
