# Generated by Django 5.2.7 on 2025-11-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0007_auditorialog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciontributaria',
            name='estado_tributario',
            field=models.CharField(default='Manual', max_length=50),
        ),
    ]
