[pytest]
DJANGO_SETTINGS_MODULE = NuamProyecto.settings
python_files = tests.py test_*.py *_tests.py
norecursedirs = .git venv env tmp .* cache
markers =
    integration: pruebas de integración
    functional: pruebas funcionales
    unit: pruebas unitarias
    django_db: pruebas con base de datos
    slow: pruebas lentas
