"""
Django settings for NuamProyecto project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import pymysql
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g(mh#an^bwx)c0b^$veid1uxpy+q)iorp@4dggx7ifusz8)4h9'

# Clave simétrica (Fernet) usada para cifrar los embeddings faciales antes de guardarlos.
# NUNCA se debe hardcodear ni subir al repo. Se define como variable de entorno en el
# servidor (ver instrucciones de despliegue). Generar una con:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
import os
FACE_ENCRYPTION_KEY ='FoAbDLnDULjd1JcjLUFAfQCt3LL_X3ztHj-k5qjl1Ac='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['32.198.111.54', 'localhost', '127.0.0.1','nuam.duckdns.org','localhost:127.0.0.1',]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auditoria',
    'declaraciones',
    'instrumentos',
    'usuarios',
    'django_extensions'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditoria.middleware.SeguridadMiddleware',
]


ROOT_URLCONF = 'NuamProyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]    

WSGI_APPLICATION = 'NuamProyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
 {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8, 
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME': 'usuarios.validators.ValidadorMayusculas', 
    },
    {
        'NAME': 'usuarios.validators.ValidadordeNumeros',
    },
    {
        'NAME': 'usuarios.validators.ValidadorCaracteresEspeciales',
        'OPTIONS': {
            'allowed_chars': '@',
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
pymysql.install_as_MySQLdb()
DATABASES ={
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'prueba_nuam_1',
        'USER': 'nuamadmin',
        'PASSWORD': 'Maxi2026@',
        'HOST':'nuam-mysql-server-2026.mysql.database.azure.com',
        'PORT':3306,
        'OPTIONS': {
            'ssl': {
                'check_hostname': False,
            },
            'charset': 'utf8mb4',
        }

    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
LOGIN_URL = 'iniciarSesion'
SERVER_EMAIL = EMAIL_HOST_USER


CSRF_TRUSTED_ORIGINS = [
    'https://nuam.duckdns.org',
]



AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_SESSION_TOKEN = os.environ.get('AWS_SESSION_TOKEN')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'nuam-media-storage-maxi')


# DynamoDB Tables
DYNAMODB_SESSIONS_TABLE = 'NUAM-Sessions'
DYNAMODB_AUDIT_TABLE = 'nuam_auditoria_seguridad'


# Configuración de S3 para archivos Media
STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}
MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/'