# Generated by Django 5.2.7 on 2025-10-19 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(blank=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('genero', models.CharField(blank=True, choices=[('', 'Select'), ('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], max_length=40)),
                ('telefono', models.CharField(max_length=60)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, choices=[('', 'Select'), ('Chile', 'Chile'), ('Perú', 'Perú'), ('Colombia', 'Colombia')], max_length=100)),
                ('region', models.CharField(blank=True, max_length=40)),
                ('comuna', models.CharField(blank=True, max_length=70)),
                ('contraseña_hash', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
            options={
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
