# Generated by Django 5.2.7 on 2025-11-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Chile', 'Chile')], max_length=100),
        ),
    ]
