# Generated by Django 5.2.7 on 2025-11-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
