# Generated by Django 5.2.7 on 2025-11-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_estado_auditoriasesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriasesion',
            name='detalles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditoriasesion',
            name='ip_adress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoriasesion',
            name='metodo_http',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditoriasesion',
            name='nivel_amenaza',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Critico')], default='BAJO', max_length=10),
        ),
        migrations.AddField(
            model_name='auditoriasesion',
            name='parametro_afectado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditoriasesion',
            name='payload_intentado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditoriasesion',
            name='ruta_accedida',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditoriasesion',
            name='tipo_ataque',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='auditoriasesion',
            name='tipo_evento',
            field=models.CharField(choices=[('LOGIN', 'Inicio de Sesisón'), ('LOGOUT', 'Cierre de Sesión'), ('LOGIN_FALLIDO', 'Intento fallido'), ('INYECCION_SQL', 'Intento de Inyección SQL'), ('XSS', 'Intento de Cross-Site Scripting'), ('CSRF', 'Intento CSRF'), ('ACCESO_DENEGADO', 'Acceso Denegado'), ('FUERZA_BRUTA', 'Ataque Fuerza Bruta')], default='LOGIN', max_length=50),
        ),
        migrations.AddField(
            model_name='auditoriasesion',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
