# Generated by Django 5.2.7 on 2025-11-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auditoriasesion_detalles_auditoriasesion_ip_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
