# Generated by Django 5.2.7 on 2025-11-29 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_usuario_reset_token_usuario_reset_token_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='reset_token_expiration',
        ),
    ]
