# Generated by Django 5.2.7 on 2025-10-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionJurada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_declaración', models.CharField(max_length=100)),
                ('fecha_extraccion', models.DateTimeField()),
                ('estado_declaracion', models.CharField(max_length=60)),
            ],
        ),
    ]
