# Generated by Django 5.2.7 on 2025-10-29 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaraciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cargas/')),
                ('tipo_carga', models.CharField(choices=[('montos:dj1948', 'Montos - DJ1948'), ('factores', 'Factores Tributarios')], max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completa', 'Completa'), ('fallida', 'Fallida')], max_length=20)),
                ('total_registros', models.IntegerField(default=0)),
                ('registros_exitosos', models.IntegerField(default=0)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('cargado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
