# Generated by Django 5.2.7 on 2025-11-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaraciones', '0002_cargaarchivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargaarchivo',
            name='estado',
            field=models.CharField(choices=[('procesando', 'Procesando'), ('completa', 'Completa'), ('fallida', 'Fallida')], default='procesando', max_length=20),
        ),
        migrations.AlterField(
            model_name='cargaarchivo',
            name='tipo_carga',
            field=models.CharField(choices=[('montos:dj1948', 'Montos - DJ1948'), ('factores', 'Factores Tributarios')], max_length=30),
        ),
    ]
