# Generated by Django 5.2.7 on 2025-11-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declaraciones', '0003_alter_cargaarchivo_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaracionjurada',
            old_name='tipo_declaración',
            new_name='tipo_declaracion',
        ),
    ]
