# Generated by Django 5.2.7 on 2025-10-19 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('codigo_mercado', models.CharField(blank=True, choices=[('Select', ''), ('Chile', 'Chile'), ('Perú', 'Perú'), ('Colombia', 'Colombia')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_instrumento', models.CharField(max_length=80)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.mercado')),
            ],
        ),
    ]
