# Generated by Django 5.2.7 on 2025-11-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercado',
            name='codigo_mercado',
            field=models.CharField(blank=True, choices=[('Select', ''), ('Chile', 'Chile')], max_length=20),
        ),
    ]
